version: '3'
services:
  mongodb:
    ports:
      - "27017:27017"
    container_name: mongodb
    image: mongo:7.0.1
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=test_db
